parameters:
    # entities
    orocrm_amazon.order.entity.class:                                            OroCRM\Bundle\AmazonBundle\Entity\Order
    orocrm_amazon.order_item.entity.class:                                       OroCRM\Bundle\AmazonBundle\Entity\OrderItem

    # connectors
    orocrm_amazon.provider.amazon_order_connector.class:                         OroCRM\Bundle\AmazonBundle\Provider\Connector\OrderConnector

    # normalizer
    orocrm_amazon.importexport.denormalizer.order.class:                         OroCRM\Bundle\AmazonBundle\ImportExport\Serializer\OrderDenormalizer

    # strategies
    orocrm_amazon.import_strategy.order.add_or_update.class:                     OroCRM\Bundle\AmazonBundle\ImportExport\Strategy\OrderStrategy

services:
    # connectors
    orocrm_amazon.provider.amazon_order_connector:
        class: %orocrm_amazon.provider.amazon_order_connector.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        tags:
          - { name: oro_integration.connector, type: order, channel_type: amazon }

    # Normalizers / Denormalizers
    orocrm_amazon.importexport.denormalizer.order:
        class: %orocrm_amazon.importexport.denormalizer.order.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @orocrm_amazon.order.factory
        tags:
            - { name: oro_importexport.normalizer }

    # strategies
    orocrm_amazon.import.strategy.order.add_or_update:
        class: %orocrm_amazon.import_strategy.order.add_or_update.class%
        arguments:
            - @oro_importexport.strategy.import.helper

    # Processors
    orocrm_amazon.importexport.processor.import_order:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setStrategy, [@orocrm_amazon.import.strategy.order.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_amazon.order.entity.class%, alias: orocrm_amazon.add_or_update_order }
