parameters:
    # entities
    eltrino_amazon.order.entity.class:                                            OroCRM\Bundle\AmazonBundle\Entity\Order
    eltrino_amazon.order_item.entity.class:                                       OroCRM\Bundle\AmazonBundle\Entity\OrderItem

    # connectors
    eltrino_amazon.provider.amazon_order_connector.class:                         OroCRM\Bundle\AmazonBundle\Provider\AmazonOrderConnector

    # normalizer
    eltrino_amazon.importexport.denormalizer.order.class:                         OroCRM\Bundle\AmazonBundle\ImportExport\Serializer\OrderDenormalizer

    # strategies
    eltrino_amazon.import_strategy.order.add_or_update.class:                     OroCRM\Bundle\AmazonBundle\ImportExport\Strategy\OrderStrategy

services:
    # connectors
    eltrino_amazon.provider.amazon_order_connector:
        class: %eltrino_amazon.provider.amazon_order_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @oro_integration.provider.connector_context_mediator
          - @eltrino_amazon.amazon_rest_client.factory
          - @eltrino_amazon.filters.factory
        tags:
          - { name: oro_integration.connector, type: order, channel_type: amazon }

    # Normalizers / Denormalizers
    eltrino_amazon.importexport.denormalizer.order:
        class: %eltrino_amazon.importexport.denormalizer.order.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @eltrino_amazon.order.factory
        tags:
            - { name: oro_importexport.normalizer }

    # strategies
    eltrino_amazon.import.strategy.order.add_or_update:
        class: %eltrino_amazon.import_strategy.order.add_or_update.class%
        arguments:
            - @oro_importexport.strategy.import.helper

    # Processors
    eltrino_amazon.importexport.processor.import_order:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setStrategy, [@eltrino_amazon.import.strategy.order.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %eltrino_amazon.order.entity.class%, alias: eltrino_amazon.add_or_update_order }
